/** Public blog, for «На сайте» links from the article editor. */
export const BLOG_URL = (import.meta.env.VITE_BLOG_URL || "https://bilimtrack.kg/blog").replace(/\/$/, "");

export const routes = {
  login: "/login",
  home: "/",
  metrics: "/metrics",
  leads: "/leads",
  tickets: "/tickets",
  ticket: (id: string | number) => `/tickets/${id}`,
  ticketStates: "/tickets-states",
  ticketPriority: "/tickets-priority",
  ideas: "/ideas",
  orgs: "/orgs",
  org: (id: string | number) => `/orgs/${id}`,
  orgNew: "/orgs-new",
  onboarding: "/onboarding",
  licenses: "/licenses",
  accounts: "/accounts",
  account: (login: string) => `/accounts/${login}`,
  plans: "/plans",
  plan: (code: string) => `/plans/${code}`,
  subscriptions: "/subscriptions",
  payments: "/payments",
  providers: "/providers",
  orgBilling: "/org-billing",
  channels: "/channels",
  inbox: "/inbox",
  templates: "/templates",
  tasks: "/tasks",
  posts: "/posts",
  postEditor: "/posts/editor",
  postEdit: (id: string) => `/posts/editor/${id}`,
  dicts: "/dicts",
  media: "/media",
  audit: "/audit",
  logins: "/logins",
  system: "/system",
  errors: "/errors",
  team: "/team",
  profile: "/profile",
  moderation: "/moderation",
  denied: "/denied",
} as const;

