export const routes = {
  login: "/login",
  home: "/",
  metrics: "/metrics",
  health: "/health",
  leads: "/leads",
  funnel: "/funnel",
  tickets: "/tickets",
  ticket: (id: string) => `/tickets/${id}`,
  ticketStates: "/tickets-states",
  ticketPriority: "/tickets-priority",
  ideas: "/ideas",
  orgs: "/orgs",
  org: (slug: string) => `/orgs/${slug}`,
  orgNew: "/orgs-new",
  onboarding: "/onboarding",
  licenses: "/licenses",
  accounts: "/accounts",
  account: (login: string) => `/accounts/${login}`,
  accountSession: (login: string) => `/accounts/${login}/session`,
  lists: "/lists",
  announcements: "/announcements",
  plans: "/plans",
  plan: (code: string) => `/plans/${code}`,
  subscriptions: "/subscriptions",
  payments: "/payments",
  providers: "/providers",
  orgBilling: "/org-billing",
  channels: "/channels",
  inbox: "/inbox",
  templates: "/templates",
  tasks: "/tasks",
  posts: "/posts",
  postEditor: "/posts/editor",
  dicts: "/dicts",
  media: "/media",
  audit: "/audit",
  logins: "/logins",
  system: "/system",
  errors: "/errors",
  team: "/team",
  denied: "/denied",
} as const;

/** "Today" in the mock data set — the design is pinned to 20 Sep 2026. */
export const MOCK_TODAY_LABEL = "суббота, 20 сентября · Asia/Almaty";
